drop table if exists Animal;
drop sequence Animal_SEQ;
drop table if exists Animal;
drop sequence Animal_SEQ;
drop table if exists Animal;
drop sequence Animal_SEQ;
drop table if exists Animal;
drop sequence Animal_SEQ;
drop table if exists Animal;
drop sequence Animal_SEQ;
